/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup gpu
 *
 * Nuru: accessors for the embedded Vulkan hardware ray-tracing GLSL kernels.
 * The kernel sources live in `vulkan/kernels/*.glsl` and are embedded via datatoc.
 */

#pragma once

/* Generated by datatoc from vulkan/kernels/*.glsl. */
extern "C" char datatoc_vk_nuru_trace_override_glsl[];
extern "C" char datatoc_vk_nuru_directional_shadow_glsl[];
extern "C" char datatoc_vk_nuru_directional_hit_shadow_glsl[];
extern "C" char datatoc_vk_nuru_environment_visibility_glsl[];
extern "C" char datatoc_vk_nuru_hit_environment_visibility_glsl[];
extern "C" char datatoc_vk_nuru_local_shadow_glsl[];
extern "C" char datatoc_vk_nuru_local_hit_shadow_glsl[];
extern "C" char datatoc_vk_nuru_oidn_pack_glsl[];
extern "C" char datatoc_vk_nuru_oidn_unpack_glsl[];

namespace blender::gpu::vulkan::nuru_kernels {

inline const char *trace_override_glsl()
{
  return datatoc_vk_nuru_trace_override_glsl;
}
inline const char *directional_shadow_glsl()
{
  return datatoc_vk_nuru_directional_shadow_glsl;
}
inline const char *directional_hit_shadow_glsl()
{
  return datatoc_vk_nuru_directional_hit_shadow_glsl;
}
inline const char *environment_visibility_glsl()
{
  return datatoc_vk_nuru_environment_visibility_glsl;
}
inline const char *hit_environment_visibility_glsl()
{
  return datatoc_vk_nuru_hit_environment_visibility_glsl;
}
inline const char *local_shadow_glsl()
{
  return datatoc_vk_nuru_local_shadow_glsl;
}
inline const char *local_hit_shadow_glsl()
{
  return datatoc_vk_nuru_local_hit_shadow_glsl;
}
inline const char *oidn_pack_glsl()
{
  return datatoc_vk_nuru_oidn_pack_glsl;
}
inline const char *oidn_unpack_glsl()
{
  return datatoc_vk_nuru_oidn_unpack_glsl;
}

}  // namespace blender::gpu::vulkan::nuru_kernels
