/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#ifdef GPU_SHADER
#  pragma once
#  include "gpu_shader_compat.hh"

#  include "draw_view_infos.hh"
#  include "eevee_common_infos.hh"
#  include "eevee_light_infos.hh"
#  include "eevee_lightprobe_infos.hh"
#  include "eevee_raytrace_shared.hh"
#  include "eevee_sampling_infos.hh"
#  include "eevee_shadow_infos.hh"
#  include "eevee_uniform_infos.hh"
#endif

#ifdef GLSL_CPP_STUBS
#  define SPHERE_PROBE
#endif

#include "eevee_defines.hh"
#include "gpu_shader_create_info.hh"

/* -------------------------------------------------------------------- */
/** \name Ray tracing Pipeline
 * \{ */

GPU_SHADER_CREATE_INFO(eevee_ray_tile_classify)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_global_ubo)
TYPEDEF_SOURCE("draw_shader_shared.hh")
IMAGE_FREQ(0, RAYTRACE_TILEMASK_FORMAT, write, uimage2DArray, tile_raytrace_denoise_img, PASS)
IMAGE_FREQ(1, RAYTRACE_TILEMASK_FORMAT, write, uimage2DArray, tile_raytrace_tracing_img, PASS)
IMAGE_FREQ(2, RAYTRACE_TILEMASK_FORMAT, write, uimage2DArray, tile_horizon_denoise_img, PASS)
IMAGE_FREQ(3, RAYTRACE_TILEMASK_FORMAT, write, uimage2DArray, tile_horizon_tracing_img, PASS)
COMPUTE_SOURCE("eevee_ray_tile_classify_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_tile_compact)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
TYPEDEF_SOURCE("draw_shader_shared.hh")
IMAGE_FREQ(0, RAYTRACE_TILEMASK_FORMAT, read, uimage2DArray, tile_raytrace_denoise_img, PASS)
IMAGE_FREQ(1, RAYTRACE_TILEMASK_FORMAT, read, uimage2DArray, tile_raytrace_tracing_img, PASS)
STORAGE_BUF(0, read_write, DispatchCommand, raytrace_tracing_dispatch_buf)
STORAGE_BUF(1, read_write, DispatchCommand, raytrace_denoise_dispatch_buf)
STORAGE_BUF(4, write, uint, raytrace_tracing_tiles_buf[])
STORAGE_BUF(5, write, uint, raytrace_denoise_tiles_buf[])
SPECIALIZATION_CONSTANT(int, closure_index, 0)
SPECIALIZATION_CONSTANT(int, resolution_scale, 1)
COMPUTE_SOURCE("eevee_ray_tile_compact_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_trace_tile_compact)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_global_ubo)
TYPEDEF_SOURCE("draw_shader_shared.hh")
IMAGE(0, SFLOAT_16_16_16_16, read, image2D, ray_data_img)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, read, image2D, ray_time_img)
STORAGE_BUF(0, read_write, DispatchCommand, hardware_trace_dispatch_buf)
STORAGE_BUF(4, write, uint, hardware_trace_tiles_buf[])
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
COMPUTE_SOURCE("eevee_ray_hardware_trace_tile_compact_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_direct_light_tile_compact)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(64, 1)
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
TYPEDEF_SOURCE("draw_shader_shared.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_light_data)
STORAGE_BUF(6, read_write, DispatchCommand, hardware_direct_light_dispatch_buf)
STORAGE_BUF(7, write, HardwareDirectLightWorkTile, hardware_direct_light_work_tiles_buf[])
COMPUTE_SOURCE("eevee_ray_hardware_direct_light_tile_compact_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_direct_light_visibility)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(1, 1)
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
TYPEDEF_SOURCE("draw_shader_shared.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_light_data)
ADDITIONAL_INFO(eevee_sampling_data)
SAMPLER(0, sampler2DArray, hardware_rt_shadow_visibility_tx)
STORAGE_BUF(4, read, HardwareDirectLightWorkTile, hardware_direct_light_work_tiles_buf[])
STORAGE_BUF(5, write, HardwareDirectLightVisibilitySample, hardware_direct_light_visibility_samples_buf[])
COMPUTE_SOURCE("eevee_ray_hardware_direct_light_visibility_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_direct_light_accum)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(1, 1)
TYPEDEF_SOURCE("eevee_defines.hh")
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
TYPEDEF_SOURCE("draw_shader_shared.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(draw_object_infos)
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_light_data)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_utility_texture)
IMAGE(0, RAYTRACE_RADIANCE_FORMAT, write, image2D, out_direct_light_accum_img)
SAMPLER(1, sampler2DDepth, depth_tx)
STORAGE_BUF(12, read, HardwareDirectLightWorkTile, hardware_direct_light_work_tiles_buf[])
STORAGE_BUF(13, read, HardwareDirectLightVisibilitySample, hardware_direct_light_visibility_samples_buf[])
COMPUTE_SOURCE("eevee_ray_hardware_direct_light_accum_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_direct_light_denoise)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(1, 1)
TYPEDEF_SOURCE("eevee_defines.hh")
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
TYPEDEF_SOURCE("draw_shader_shared.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(draw_object_infos)
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_light_data)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_utility_texture)
SAMPLER(0, sampler2DDepth, depth_tx)
SAMPLER(1, sampler2DArray, hardware_rt_shadow_visibility_tx)
IMAGE(4, RAYTRACE_RADIANCE_FORMAT, read, image2D, in_direct_light_accum_img)
IMAGE(5, RAYTRACE_RADIANCE_FORMAT, write, image2D, out_direct_light_denoised_img)
IMAGE(6, SFLOAT_32, write, image2D, out_direct_light_depth_img)
IMAGE(7, RAYTRACE_TILEMASK_FORMAT, write, uimage2D, direct_light_tilemask_img)
STORAGE_BUF(12, read, HardwareDirectLightWorkTile, hardware_direct_light_work_tiles_buf[])
STORAGE_BUF(13, read, HardwareDirectLightVisibilitySample, hardware_direct_light_visibility_samples_buf[])
STORAGE_BUF(14, read, LightData, light_buf_no_cull[])
COMPUTE_SOURCE("eevee_ray_hardware_direct_light_denoise_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_indirect_gi_cache_store)
DO_STATIC_COMPILATION()
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_gbuffer_data)
SAMPLER(1, sampler2DDepth, depth_tx)
SAMPLER(2, sampler2D, combined_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2DArray, out_indirect_gi_radiance_cache_img)
IMAGE(1, SFLOAT_16_16_16_16, write, image2DArray, out_indirect_gi_position_cache_img)
IMAGE(2, SFLOAT_16_16_16_16, write, image2DArray, out_indirect_gi_normal_cache_img)
PUSH_CONSTANT(int, cache_face_index)
COMPUTE_SOURCE("eevee_ray_hardware_indirect_gi_cache_store_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_tile_compact)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
TYPEDEF_SOURCE("draw_shader_shared.hh")
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, read, image2D, ray_time_img)
IMAGE(4, SFLOAT_16_16_16_16, read, image2D, hit_normal_img)
STORAGE_BUF(0, read_write, DispatchCommand, hardware_resolve_dispatch_buf)
STORAGE_BUF(4, write, uint, hardware_resolve_tiles_buf[])
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
COMPUTE_SOURCE("eevee_ray_hardware_tile_compact_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hit_eval_count)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, read, image2D, ray_time_img)
IMAGE(6, UINT_32_32_32_32, read, uimage2D, hit_identity_img)
SAMPLER(0, sampler2DDepth, depth_tx)
STORAGE_BUF(0, read_write, uint, hit_eval_count_buf[])
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
PUSH_CONSTANT(int, scene_entry_count)
COMPUTE_SOURCE("eevee_ray_hit_eval_count_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hit_eval_prefix)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(64, 1)
TYPEDEF_SOURCE("draw_shader_shared.hh")
STORAGE_BUF(0, read, uint, hit_eval_count_buf[])
STORAGE_BUF(1, write, uint, hit_eval_offset_buf[])
STORAGE_BUF(2, write, uint, hit_eval_cursor_buf[])
STORAGE_BUF(3, write, DrawCommandArray, hit_eval_indirect_draw_buf[])
PUSH_CONSTANT(int, scene_entry_count)
COMPUTE_SOURCE("eevee_ray_hit_eval_prefix_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hit_eval_compact)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, read, image2D, ray_time_img)
IMAGE(2, UINT_32_32_32_32, read_write, uimage2D, hit_identity_img)
IMAGE(3, SFLOAT_16_16_16_16, read, image2D, hit_material_img)
IMAGE(4, SFLOAT_16_16_16_16, read, image2D, hit_normal_img)
IMAGE(7, SFLOAT_16_16_16_16, read, image2D, hit_barycentric_img)
SAMPLER(0, sampler2DDepth, depth_tx)
SAMPLER(1, sampler2D, hit_world_position_tx)
STORAGE_BUF(1, read, uint, hit_eval_offset_buf[])
STORAGE_BUF(2, read_write, uint, hit_eval_cursor_buf[])
STORAGE_BUF(3, read, uint, hit_eval_resource_id_buf[])
STORAGE_BUF(4, write, HardwareHitEvalRecord, hit_eval_list_buf[])
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
PUSH_CONSTANT(int, scene_entry_count)
COMPUTE_SOURCE("eevee_ray_hit_eval_compact_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_generate)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
TYPEDEF_SOURCE("eevee_raytrace_shared.hh")
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_utility_texture)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, out_ray_data_img)
STORAGE_BUF(4, read, uint, tiles_coord_buf[])
SPECIALIZATION_CONSTANT(int, closure_index, 0)
COMPUTE_SOURCE("eevee_ray_generate_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_hardware_fast_gi_update)
DO_STATIC_COMPILATION()
LOCAL_GROUP_SIZE(4, 4, 4)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
SAMPLER(0, sampler2DDepth, depth_tx)
SAMPLER(1, sampler2D, input_radiance_tx)
IMAGE(0, SFLOAT_16_16_16_16, read_write, image3D, out_fast_gi_img)
IMAGE(1, SFLOAT_16_16_16_16, read_write, image3D, out_fast_gi_visibility_img)
SPECIALIZATION_CONSTANT(int, cascade_index, 0)
COMPUTE_SOURCE("eevee_ray_trace_hardware_fast_gi_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_trace_fallback)
DO_STATIC_COMPILATION()
/* The use of UTIL_TEXEL doesn't directly pull the builtins from eevee_defines.hh. */
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_lightprobe_data)
IMAGE(0, SFLOAT_16_16_16_16, read, image2D, ray_data_img)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, write, image2D, ray_time_img)
IMAGE(2, RAYTRACE_RADIANCE_FORMAT, write, image2D, ray_radiance_img)
SAMPLER(1, sampler2DDepth, depth_tx)
SAMPLER(15, sampler2D, hardware_rt_environment_visibility_tx)
SAMPLER(11, sampler3D, hardware_fast_gi_tx)
SAMPLER(12, sampler3D, hardware_fast_gi_visibility_tx)
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
SPECIALIZATION_CONSTANT(bool, use_hardware_rt_environment_visibility, false)
SPECIALIZATION_CONSTANT(int, closure_index, 0)
COMPUTE_SOURCE("eevee_ray_trace_fallback_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_trace_hardware_lighting)
DO_STATIC_COMPILATION()
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(eevee_lightprobe_data)
ADDITIONAL_INFO(eevee_light_data)
ADDITIONAL_INFO(eevee_shadow_data)
ADDITIONAL_INFO(eevee_utility_texture)
ADDITIONAL_INFO(draw_object_infos)
DEFINE("SHADOW_DISPATCH_HAS_HARDWARE_RT")
DEFINE("SHADOW_DISPATCH_USE_GLOBAL_TEXEL")
IMAGE(0, SFLOAT_16_16_16_16, read, image2D, ray_data_img)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, read_write, image2D, ray_time_img)
IMAGE(2, SFLOAT_16_16_16_16, read, image2D, hit_albedo_img)
IMAGE(3, SFLOAT_16_16_16_16, read, image2D, hit_material_img)
IMAGE(4, SFLOAT_16_16_16_16, read, image2D, hit_normal_img)
IMAGE(5, SFLOAT_16_16_16_16, read, image2D, hit_position_img)
IMAGE(6, RAYTRACE_RADIANCE_FORMAT, read_write, image2D, ray_radiance_img)
IMAGE(7, UINT_32_32_32_32, read, uimage2D, hit_identity_img)
IMAGE(8, SFLOAT_16_16_16_16, read_write, image2D, hardware_caustics_img)
SAMPLER(1, sampler2DDepth, depth_tx)
SAMPLER(9, sampler2DArray, hardware_rt_shadow_visibility_tx)
SAMPLER(12, sampler2D, radiance_front_tx)
SAMPLER(13, sampler2D, radiance_back_tx)
SAMPLER(14, sampler2D, hit_world_position_tx)
SAMPLER(15, sampler2D, hardware_rt_environment_visibility_tx)
SAMPLER(33, sampler2D, hit_transmission_layer_tx)
SAMPLER(8, sampler2D, hardware_rt_hit_environment_visibility_tx)
SAMPLER(11, sampler3D, hardware_fast_gi_tx)
SAMPLER(10, sampler3D, hardware_fast_gi_visibility_tx)
SAMPLER(24, sampler2D, layered_receiver_throughput_tx)
SAMPLER(25, sampler2D, layered_receiver_ray_time_tx)
SAMPLER(26, sampler2D, layered_receiver_ray_radiance_tx)
SAMPLER(27, sampler2D, layered_receiver_hit_albedo_tx)
SAMPLER(28, sampler2D, layered_receiver_hit_material_tx)
SAMPLER(29, sampler2D, layered_receiver_hit_normal_tx)
SAMPLER(30, sampler2D, layered_receiver_hit_position_tx)
SAMPLER(31, usampler2D, layered_receiver_hit_identity_tx)
SAMPLER(32, sampler2D, layered_receiver_world_position_tx)
SAMPLER(34, sampler2D, transmission_receiver_throughput_tx)
SAMPLER(35, sampler2D, transmission_receiver_ray_time_tx)
SAMPLER(36, sampler2D, transmission_receiver_ray_radiance_tx)
SAMPLER(37, sampler2D, transmission_receiver_hit_albedo_tx)
SAMPLER(38, sampler2D, transmission_receiver_hit_material_tx)
SAMPLER(39, sampler2D, transmission_receiver_hit_normal_tx)
SAMPLER(40, sampler2D, transmission_receiver_hit_position_tx)
SAMPLER(41, usampler2D, transmission_receiver_hit_identity_tx)
SAMPLER(42, sampler2D, transmission_receiver_world_position_tx)
SAMPLER(43, sampler2DArray, hardware_indirect_gi_radiance_cache_tx)
SAMPLER(44, sampler2DArray, hardware_indirect_gi_position_cache_tx)
SAMPLER(45, sampler2DArray, hardware_indirect_gi_normal_cache_tx)
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
STORAGE_BUF(14, read, LightData, light_buf_no_cull[])
SPECIALIZATION_CONSTANT(bool, use_hardware_environment, false)
SPECIALIZATION_CONSTANT(bool, use_hardware_rt_shadows, false)
SPECIALIZATION_CONSTANT(bool, use_hardware_rt_environment_visibility, false)
SPECIALIZATION_CONSTANT(int, closure_index, 0)
COMPUTE_SOURCE("eevee_ray_trace_hardware_lighting_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_trace_scene_final_specular_resolve)
DO_STATIC_COMPILATION()
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_gbuffer_data)
DEFINE("SCENE_FINAL_SPECULAR_RESOLVE_PASS")
SAMPLER(0, sampler2D, indirect_radiance_1_tx)
SAMPLER(1, sampler2D, indirect_radiance_2_tx)
SAMPLER(2, sampler2D, indirect_radiance_3_tx)
IMAGE(3, SFLOAT_16_16_16_16, read_write, image2D, combined_img)
IMAGE(4, SFLOAT_16_16_16_16, read_write, image2DArray, rp_color_img)
COMPUTE_SOURCE("eevee_ray_generate_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_trace_planar)
DO_STATIC_COMPILATION()
/* The use of UTIL_TEXEL doesn't directly pull the builtins from eevee_defines.hh. */
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
DEFINE("PLANAR_PROBES")
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_lightprobe_data)
ADDITIONAL_INFO(eevee_lightprobe_planar_data)
IMAGE(0, SFLOAT_16_16_16_16, read_write, image2D, ray_data_img)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, write, image2D, ray_time_img)
IMAGE(2, RAYTRACE_RADIANCE_FORMAT, write, image2D, ray_radiance_img)
SAMPLER(2, sampler2DDepth, depth_tx)
SAMPLER(11, sampler3D, hardware_fast_gi_tx)
SAMPLER(12, sampler3D, hardware_fast_gi_visibility_tx)
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
SPECIALIZATION_CONSTANT(bool, use_hardware_specular_scene, false)
SPECIALIZATION_CONSTANT(int, closure_index, 0)
COMPUTE_SOURCE("eevee_ray_trace_planar_comp.glsl")
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_ray_trace_screen)
DO_STATIC_COMPILATION()
/* The use of UTIL_TEXEL doesn't directly pull the builtins from eevee_defines.hh. */
BUILTINS(BuiltinBits::GLOBAL_INVOCATION_ID)
LOCAL_GROUP_SIZE(RAYTRACE_GROUP_SIZE, RAYTRACE_GROUP_SIZE)
TYPEDEF_SOURCE("eevee_defines.hh")
ADDITIONAL_INFO(eevee_global_ubo)
ADDITIONAL_INFO(eevee_sampling_data)
ADDITIONAL_INFO(eevee_gbuffer_data)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_hiz_data)
ADDITIONAL_INFO(eevee_lightprobe_data)
IMAGE(0, SFLOAT_16_16_16_16, read_write, image2D, ray_data_img)
IMAGE(1, RAYTRACE_RAYTIME_FORMAT, write, image2D, ray_time_img)
IMAGE(2, RAYTRACE_RADIANCE_FORMAT, write, image2D, ray_radiance_img)
IMAGE(3, SFLOAT_16_16_16_16, write, image2D, screen_continuation_img)
IMAGE(4, RAYTRACE_VARIANCE_FORMAT, write, image2D, screen_ownership_img)
SAMPLER(0, sampler2DDepth, depth_tx)
SAMPLER(1, sampler2D, radiance_front_tx)
SAMPLER(2, sampler2D, radiance_back_tx)
SAMPLER(4, sampler2D, hiz_front_tx)
SAMPLER(5, sampler2D, hiz_back_tx)
SAMPLER(14, sampler2D, ownership_history_tx)
SAMPLER(15, sampler2D, hardware_rt_environment_visibility_tx)
SAMPLER(11, sampler3D, hardware_fast_gi_tx)
SAMPLER(12, sampler3D, hardware_fast_gi_visibility_tx)
STORAGE_BUF(5, read, uint, tiles_coord_buf[])
COMPUTE_SOURCE("eevee_ray_trace_screen_comp.glsl")
/* Metal: Provide compiler with hint to tune per-thread resource allocation. */
MTL_MAX_TOTAL_THREADS_PER_THREADGROUP(400)
SPECIALIZATION_CONSTANT(bool, trace_refraction, true)
SPECIALIZATION_CONSTANT(bool, use_hardware_rt_environment_visibility, false)
SPECIALIZATION_CONSTANT(bool, use_hardware_specular_scene, false)
SPECIALIZATION_CONSTANT(bool, use_hardware_hybrid_retrace, false)
SPECIALIZATION_CONSTANT(bool, use_screen_ownership_history, false)
SPECIALIZATION_CONSTANT(int, closure_index, 0)
COMPUTE_SOURCE("eevee_ray_trace_screen_comp.glsl")
GPU_SHADER_CREATE_END()

/** \} */
